import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { PWAProvider } from "next-pwa-pack";
import { Toaster } from "sonner";
import { ConnectivityListener } from "@/components/ConnectivityListener";

export const metadata: Metadata = {
  title: "Books app",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    title: "Books app",
    statusBarStyle: "default",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#1c1c1c" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />

        <meta name="application-name" content="Books app" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Books app" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="msapplication-TileColor" content="#1c1c1c" />
        <meta name="msapplication-tap-highlight" content="no" />
      </head>
      <body className={`antialiased`}>
        <PWAProvider>
          <Providers>
            <Toaster duration={1500} position="top-right" />
            <ConnectivityListener />
            {children}
          </Providers>
        </PWAProvider>
      </body>
    </html>
  );
}
