import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { PWAProvider } from "next-pwa-pack";
import { Toaster } from "sonner";
import { ConnectivityListener } from "@/components/ConnectivityListener";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <PWAProvider>
          <Providers>
            <Toaster duration={1500} position="top-right" />
            <ConnectivityListener />
            {children}
          </Providers>
        </PWAProvider>
      </body>
    </html>
  );
}
